# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='user',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
