# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_auto_20160115_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='user',
            field=models.IntegerField(),
        ),
    ]
